
name: build d'un projet

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Téléchargement des sources || cloner le repertoire 
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: '88.0.4324.96'
        target-directory : ./Drivers
    - name : Download and configure chromeDriver.exe 
      run: |
          wget -O chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver.zip
          chmod +x chromedriver
          mv chromedriver Drivers/
 
    - name: Start Xvfb
      run: |
        export DISPLAY=:99
        sudo apt-get update
        sudo apt-get install -y xvfb
        sudo Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run unit tests 
      run: mvn -e test

    - name: Trigger Jenkins Deployment
      uses: actions/github-script@v3
      with:
        script: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"project": "http://localhost:8008/job/deploy", "pipeline": "deploy", "branch": "dev"}' \
            http://localhost:8008/job/deploy/buildWithParameters
